<main>
    <form action="/shortener" method="POST" class="form-url">
        <label>Insira uma URL</label>
        <input type="text" name="url">
        <button type="submit">Encurtar</button>
    </form>

    <section>
        <?php foreach($this->view->data as $data){ ?>
            <div class="item">
                <a href="<?php echo $this->view->url .$data['id']?>" target="_blank" rel="noopener noreferrer">
                    <?php echo $this->view->url .$data['id']?>
                </a>

                <div class="item-info">
                    <span><?php echo $data['url'] ?></span>
    
                    <form action="/remove" method="POST">
                        <input type="hidden" name="id">
                        <button type="submit">Deletar</button>   
                    </form>
                </div>
            
            </div>
        <?php } ?>
    </section>
</main>
